let cars = [
  {
    img: "../images/car1.png",
    name: "Ford Fiesta",
    type: "Economy Car",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    img: "../images/car2.png",
    name: "Nissan Versa",
    type: "Compact Car",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Toyota Corolla",
    type: "Mid-size Car",
    img: "../images/car3.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Nissan Rogue",
    type: "Economy Car",
    img: "../images/car4.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Ford Fiesta",
    type: "Economy Car",
    img: "../images/car5.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Ford Fiesta",
    type: "Economy Car",
    img: "../images/car6.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Ford Fiesta",
    type: "Economy Car",
    img: "../images/car7.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Ford Fiesta",
    type: "Economy Car",
    img: "../images/car8.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Ford Fiesta",
    type: "Economy Car",
    img: "../images/car9.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Ford Fiesta",
    type: "Economy Car",
    img: "../images/car10.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Ford Fiesta",
    type: "Economy Car",
    img: "../images/car11.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Ford Fiesta",
    type: "Economy Car",
    img: "../images/car12.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Ford Fiesta",
    type: "Economy Car",
    img: "../images/car13.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Ford Fiesta",
    type: "Economy Car",
    img: "../images/car14.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Ford Fiesta",
    type: "Economy Car",
    img: "../images/car15.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    name: "Ford Fiesta",
    type: "Economy Car",
    img: "../images/car16.png",
     imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
];
